<!DOCTYPE html>

<html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Dogger Out </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="shortcut icon" href="<?php echo $this->basePath('') ?>/img/favicon.png" type="image/x-icon">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath('') ?>/css/bootstrap.min.css">
        <!-- Fonts from Font Awsome -->
        <link rel="stylesheet" href="<?php echo $this->basePath('') ?>/css/font-awesome.min.css">
         <!-- Magnific popup -->
        <link rel="stylesheet" href="<?php echo $this->basePath('') ?>/css/magnific-popup.css">
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="<?php echo $this->basePath('') ?>/css/main.css">

        <!-- Color options -->
        <link rel="stylesheet" href="<?php echo $this->basePath('') ?>/css/colors/green.css">
        <!-- Feature detection -->
        <script src="<?php echo $this->basePath('') ?>/js/modernizr-2.6.2.min.js"></script>
        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="js/plugins/html5shiv.js"></script>
          <script src="js/plugins/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    <!-- welcome begins -->
    <section id="page-welcome" class="page-welcome">
      <div>
          <ul class="slider-controls">
              <li><a id="vegas-next" class="next" href="#"></a></li>
              <li><a id="vegas-prev" class="prev" href="#"></a></li>
          </ul>
        </div>
        <div class="container">
            <div class="row" style="margin-top: 0px;">
                  <!-- Text Slider -->


                    <div class="flexslider">
                      <img src="<?php echo $this->basePath('') ?>/img/logo-header.png">
                      <br><br>
                      <ul class="home-slides">
                        <li>
                        	 Paseamos a tu perro de una manera <span>segura y divertida</span>
                        </li>
                        <li>
                          ¿No tienes tiempo de pasear a tu mascota? <span>¡Tenemos la solución!</span>
                        </li>
                        <li>
                           ¿Amas a los perros y quieres formar parte de nuestro equipo de paseadores?
                        </li>                        
                      </ul>
					           </div>
                     
                     <br><br>
						
						<a href="#" class="btn btn-default">
                          <span data-hover="Regístrate">Regístrate</span>
                        </a>

                         <br><br>
                </div>
        </div>
    </section><!-- welcome ends -->
    <!-- Nav starts -->
     <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="<?php echo $this->basePath('') ?>/img/logo.png" alt=""></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav nav-effect" id="main-menu">
            <li><a href="#page-welcome"><span data-hover="Home">Inicio</span></a></li>
            <li><a href="#page-about"><span data-hover="About">Dogger Out</span></a></li>
            <li><a href="#page-team"><span data-hover="Team">¿Como funciona?</span></a></li>
            <li><a href="#page-services"><span data-hover="Services">Tracking</span></a></li>
            <li><a href="#page-pricing"><span data-hover="Pricing">Seguro</span></a></li>
            <li><a href="#page-contact"><span data-hover="Contact">Contacto</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div><!-- Nav ends -->
    <!-- about begins -->

 		<section id="page-about" class="page-about">
		      <div class="container">
		                <header class="section-header">
		                    <h2 class="section-title">¿Qué es Dogger Out?</h2>
		                    <div class="spacer"></div>
		                    <p class="section-subtitle">DoggerOut es una compañía enfocada en ofrecer a sus clientes el mejor servicio de paseadores de perros de Colombia. Brindamos un servicio profesional y personalizado tanto para el consentido de la casa como para su dueño, generando una experiencia inigualable, segura y divertida. </p>
		                </header>
		      </div> 
		</section><!-- about ends -->


            <section id="parallax-quote" class="parallax">
                <div class="parallax-background5 parallax-background"></div><!-- parallax bg image -->
                <div class="overlay"></div>
                <div class="container">
                  <div class="row">
                      <div class="col-md-12">
                        <div class="parallax-content">
                          <blockquote>
                              <i class="fa fa-quote-left"></i> El perro es el único ser que te quiere más que tú mismo <i class="fa fa-quote-right"></i>
                              <footer>- Fritz Von Unruch </footer>
                          </blockquote>
                        </div>
                      </div>
                  </div>
                </div>
            </section><!-- parallax quote end -->

    <section id="page-team" class="page-services">
       <div class="container">
                 <header class="section-header">
                    <h2 class="section-title"><span>¿Cómo funciona?</span></h2>
                      <div class="spacer"></div>
                    <p class="section-subtitle"></p>
                </header>
                <div class="row">
                  
                  <div class="col-md-3 text-center">
                    <div class="research hi-icon-effect-1">
                      <i class="hi-icon">1</i>
                    </div>
                    <header class="process-header">
                      <h3>Regístrate</h3>
                      <p>Ingresa al website y llena el formulario con tus datos.</p>
                    </header>
                  </div>
                 
                  <div class="col-md-3 text-center">
                    <div class="research hi-icon-effect-1">
                      <i class="hi-icon">2</i>
                    </div>
                    <header class="process-header">
                      <h3>Programa el paseo</h3>
                      <p> Escoge la fecha, hora y paseador para el paseo de tu mascota.</p>
                    </header>
                  </div>

                   <div class="col-md-3 text-center">
                    <div class="research hi-icon-effect-1">
                      <i class="hi-icon">3</i>
                    </div>
                    <header class="process-header">
                      <h3>Entrega tu mascota</h3>
                      <p>El paseador pasara por tu mascota a la hora fijada y lo llevara a dar un paseo muy divertido.</p>
                    </header>
                  </div>

                   <div class="col-md-3 text-center">
                    <div class="research hi-icon-effect-1">
                      <i class="hi-icon">4</i>
                    </div>
                    <header class="process-header">
                      <h3>Culmina la experiencia</h3>
                      <p>Terminado el paseo, te llegará un informe sobre el mismo y podrás evaluar al paseador.</p>
                    </header>
                  </div>
                
              </div>
    </section><!-- services ends -->

             <section id="parallax-quote" class="parallax">
                <div class="parallax-background4 parallax-background"></div><!-- parallax bg image -->
                <div class="overlay"></div>
                <div class="container">
                  <div class="row">
                      <div class="col-md-12">
                        <div class="parallax-content">
                          <blockquote>
                              <i class="fa fa-quote-left"></i> Hasta que hayas amado a un animal, una parte del alma estará dormida <i class="fa fa-quote-right"></i>
                              <footer>- Anatole France </footer>
                          </blockquote>
                        </div>
                      </div>
                  </div>
                </div>
            </section><!-- parallax quote end -->

		     <section id="page-services" class="page-about">
		      <div class="container">
		                <header class="section-header">
		                    <h2 class="section-title">Tracking Dogger Out</h2>
		                    <br><br>
		                    <!--p class="section-subtitle">Para ofrecerte el mejor servicio posible contamos con: </p-->
		                </header>
		          <div class="row">
		              <div class="col-md-6 text-center">
			                <img src="<?php echo $this->basePath('') ?>/img/servicios/tracking.png">
		              </div>
		             <div class="col-md-6 text-center">
		                <!--div class="design hi-icon-effect-1">
		                  <i class="hi-icon fa fa-male"></i>
		                </div-->
		                 <header class="process-header">
		                  <br><br>
		                  <p style="font-size: 20px; text-align: justify;">Sin importar dónde te encuentres, podrás acceder a nuestra página web y revisar la ubicación específica de tu mascota al momento y los lugares donde ha estado.</p>
		                </header>
		               </div>
		              
		          </div>
		      </div> 
		    </section><!-- about ends -->


     		<section id="parallax-quote" class="parallax">
                <div class="parallax-background3 parallax-background"></div><!-- parallax bg image -->
                <div class="overlay"></div>
                <div class="container">
                  <div class="row">
                      <div class="col-md-12">
                        <div class="parallax-content">
                          <blockquote>
                              <i class="fa fa-quote-left"></i> El perro promedio es mejor persona que la persona promedio <i class="fa fa-quote-right"></i>
                              <footer>- Andy Rooney</footer>
                          </blockquote>
                        </div>
                      </div>
                  </div>
                </div>
            </section><!-- parallax quote end -->


 			<section id="page-pricing" class="page-about">
		       <div class="container">
		                <header class="section-header">
		                    <h2 class="section-title">Seguro y Servicio Veterinario</h2>
		                    <br><br>
		                    <!--p class="section-subtitle">Para ofrecerte el mejor servicio posible contamos con: </p-->
		                </header>
		          <div class="row">
		              
		             <div class="col-md-6 text-center">
		                <!--div class="design hi-icon-effect-1">
		                  <i class="hi-icon fa fa-male"></i>
		                </div-->
		                 <header class="process-header">
		                  <br><br>
		                  <p style="font-size: 20px; text-align: justify;">Incluimos dentro del pago un Seguro para tu mascota y Servicio Veterinario a la mano, para poder abordar cualquier tipo de eventualidad que se suscite durante el paseo de la manera más responsable y eficiente, velar ante todo por la seguridad de tu perro y responder por cualquier inconveniente presentado. </p>
                     
		                </header>
		            </div>

		            <div class="col-md-6 text-center">
			                <img src="<?php echo $this->basePath('') ?>/img/servicios/veterinaria.jpg">
		              </div>
		              
		          </div>
		      </div> 
		    </section><!-- about ends -->


    <!-- highlight section begins -->
    <section class="highlight"> 
          <div class="container"> 
               <header class="section-header">
                    <h2>Somos una comunidad en crecimiento</h2>
                    <p class="section-subtitle">¿Ya eres uno de nosotros? </p>
                </header>
          <div class="row">
              <div class="col-md-3">
                <div class="count">
                <div class="counter" data-from="0" data-to="1058"></div>
                <h3>Paseos realizados</h3>
                </div>
              </div>
              <div class="col-md-3">
                 <div class="count">
                <div class="counter" data-from="0" data-to="85"></div>
                <h3>Nuevos clientes</h3>
                </div>
              </div>
              <div class="col-md-3">
                 <div class="count">
                <div class="counter" data-from="0" data-to="350"></div>
                <h3>Clientes inscritos</h3>
                </div>
              </div>
              <div class="col-md-3">
                 <div class="count">
                <div class="counter" data-from="0" data-to="520"></div>
                <h3>Paseadores</h3>
                </div>
              </div>
            </div>
          </div>
          </section><!-- highlight section ends -->
     
     <section id="page-services" class="page-services">
       <div class="container">
                 <header class="section-header">
                    <h2 class="section-title"><span>Otros Beneficios</span></h2>
                      <div class="spacer"></div>
                    <p class="section-subtitle"> Lo que nos diferencia </p>
                </header>
            <div class="row">
             
            <div class="col-md-4 ">
                <div class="service-block">
                  <div class="service-icon">
                     <i class="fa fa-comments"></i>
                    </div>
                    <h3>Atención personalizada</h3>
                     <p>Atendemos a cada cliente de manera exclusiva y atenta, buscando cubrir todos sus requerimientos.</p>
                    
               </div>
            </div>
            <div class="col-md-4">
              <div class="service-block">
                <div class="service-icon">
                      <i class="fa fa-male"></i>
                    </div>
                    <h3>Paseadores Certificados</h3>
                     <p>Contamos con estrictos filtros de seguridad y verificación para cada uno de nuestros aspirantes a Paseador.</p>
               </div>
            </div>

            <div class="col-md-4">
              <div class="service-block">
                <div class="service-icon">
                      <i class="fa fa-pencil-square"></i>
                    </div>
                    <h3>Informe de Paseo</h3>
                     <p>Al final de cada paseo se te entregará un reporte completo de las incidencias de la caminata.</p>
               </div>
            </div>

            <div class="col-md-4">
              <div class="service-block">
                <div class="service-icon">
                      <i class="fa fa-star"></i>
                    </div>
                    <h3>Evaluación de Paseadores</h3>
                     <p>Podrás evaluar el trato y el desempeño de tu paseador para que los demás usuarios lo tengan en consideración.</p>
               </div>
            </div>

            <div class="col-md-4">
              <div class="service-block">
                <div class="service-icon">
                      <i class="fa fa-calendar"></i>
                    </div>
                    <h3>Calendario de Paseos</h3>
                    <h3 style="color:black">¡Proximamente!</h3>
                     <p>Tendrás acceso al itinerario de paseos, para que puedas pautar los de tu mascota.</p>
               </div>
            </div>

            <div class="col-md-4">
              <div class="service-block">
                <div class="service-icon">
                      <i class="fa fa-exchange"></i>
                    </div>
                    <h3>Segmentación de mascotas</h3>
                     <p>Agrupamos a las mascotas por tamaño (pequeñas, medianas y grandes) para ajustar el ritmo del paseo a cada una de ellas.</p>
               </div>
            </div>


        </div>
    </section><!-- services ends -->
    
     <section id="parallax-connect" class="parallax">
                <div class="parallax-background2 parallax-background"></div><!-- parallax bg image -->
                <div class="overlay"></div>
                <div class="container">
                  <div class="row">
                      <div class="col-md-12">
                        <div class="parallax-content">
                            <header class="section-header">
                                <h2 class="section-title"><span>Conócenos</span></h2>
                                  <div class="spacer"></div>
                                    <p class="section-subtitle">Síguenos y contágiate con la alegría de nuestros Dogger Usuarios.</p>
                            </header>
                           <div class="social-icons">
                            <a href="https://www.facebook.com/DoggerOut-794973880607776/?fref=ts" class="btn btn-round btn-clear btn-facebook"><i class="fa fa-facebook"></i></a>
                            <a href="https://www.instagram.com/doggerout/" class="btn btn-round btn-clear btn-instagram"><i class="fa fa-instagram"></i></a>
                            <a href="http://www.linkedin.com/" class="btn btn-round btn-clear btn-linkedin"><i class="fa fa-linkedin-square"></i></a>           
                        </div>
                        </div>
                      </div>
                  </div>
                </div>
            </section><!-- parallax connect feed ends -->
    <!-- contact begins -->
     <section id="page-contact" class="page-contact">
          <div class="container">
              <header class="section-header">
                  <h2 class="section-title"><span>Contacto</span></h2>
                      <!--div class="spacer"></div>
                       <p class="section-subtitle">Lorem ipsum dolor sit amet, id iusto oportere mel. </p-->
              </header>
        <div class="row">
          <div class="col-md-offset-3 col-sm-6 contact-info text-center">
            <h3>Información de Contacto</h3>
            <p><i class="fa fa-map-marker"></i> Dirección: Calle 145 #17-26 Cedritos, Bogotá. </p>
            <p><i class="fa fa-phone"></i> 3016043624 </p>
            <p><i class="fa fa-envelope-o"></i> info@doggerout.com</p>
            <!--div class="gmap-wrapper">
            <iframe data-address="Little Rock, AR" frameborder="0" allowfullscreen="" data-zoom="10" data-bubble="true" class="gmap"></iframe>
          </div-->
          </div>
          
          <div class="col-sm-7">
          <h3>Mantente en contacto</h3>
              <form class="form-horizontal" id="contact-form">
        <div class="control-group">
            <label class="control-label" for="name">Nombre</label>
            <div class="controls">
                <?php echo $this->formInput($this->contact_form->get('name')); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="email">Correo Electrónico</label>
            <div class="controls">
                <input type="text" name="email" id="email" placeholder="Correo Electrónico" class="form-control input-lg">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="message">Mensaje</label>
            <div class="controls">
                <textarea name="message" id="message" rows="8" class="form-control input-lg"></textarea>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-default btn-lg btn-block">Enviar Mensaje</button>
        </div>
    </form>
          </div
        </div><!-- End row -->

        </div>
    </section> <!-- contact ends -->


        <script src="<?php echo $this->basePath('') ?>/js/jquery-1.10.2.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.queryloader2.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.parallax-1.1.3.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.flexslider.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.scrollTo.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.nav.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.sticky.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.vegas.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.isotope.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.magnific-popup.min.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.validate.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/jquery.countTo.js"></script>
        <script src="<?php echo $this->basePath('') ?>/js/waypoints.min.js"></script>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=&sensor=false"></script>
        <script src="<?php echo $this->basePath('') ?>/js/main.js"></script>

        
       <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-46627904-1', 'authenticgoods.co');
        ga('send', 'pageview');

</script>
    </body>
</html>
