<div class="container main-container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <a href="<?php echo $this->basePath('') ?>">Inicio</a> </li>
        <li> <a href="<?php echo $this->url('account', array('controller' => 'index', 'action' => 'index')) ?>">Mi Cuenta</a> </li>
        <li class="active">Ordenes</li>
      </ul>
    </div>

  
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-10">
      <div class="row userInfo">
        <?php if (isset($this->orders) && sizeof($this->orders) > 0 ): ?>
        <div class="col-lg-12">
          <h2 class="block-title-2"><span><i class="fa fa-list-alt"></i> Ordenes </span></h2>
        </div>
        
        <div class="col-xs-12 col-sm-12">
          <table class="footable">
            <thead>
              <tr>
                <th data-class="expand" data-sort-initial="true"> <span title="table sorted by this column on load">Orden ID</span> </th>
                <th data-hide="default" data-sort-ignore="true">Factura</th>
                <th data-hide="phone,tablet,default"><strong>Forma de Pago</strong></th>
                <th data-hide="phone,tablet,default"><strong>Estado de Pago</strong></th>
                <th> Total</th>
                <th data-hide='phone,tablet, default'><strong>Cantidad de productos</strong></th>
                <th data-type="numeric"> Fecha y Hora</th>
                <th data-hide="phone,tablet" data-type="numeric">Estado</th>
                <th> Acciones </th>
              </tr>
            </thead>
            <tbody>
            <?php foreach($this->orders as $order): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($order->order_id); ?></td>
                    <td><a href="<?php echo $this->url('account', array('controller' => 'OrderHistory', 'action' => 'detail', 'id' => $order->order_id)) ?>" target="_blank">#<?php echo $this->escapeHtml($order->invoice_number); ?></a></td>
                    <td> <?php echo $this->escapeHtml(is_null($order->tdc)? 'N/A': $order->tdc); ?></td>
                    <td> <?php echo $this->escapeHtml(
                            is_null($order->cod) ? 'No Emitido': ($order->cod === '00'? 'Aprobado': 'Rechazado')
                         ); ?>
                    </td>
                    <td>Bs. <?php echo $this->escapeHtml($order->total_payment); ?> </td>
                    <td><small><?php echo $this->escapeHtml($order->sum_products); ?></small> Items</td>
                    <td data-value="78025368997">
                        <?php echo $this->escapeHtml($order->date_added) ?>
                    </td>
                    <td data-value="3">
                        <?php switch($order->order_status): 
                            case 1: ?>
                                <span class="label label-warning">
                                    Por Pagar
                                </span>
                            <?php break; ?>
                            <?php case 2: ?>
                                <?php if ($order->cod): ?>
                                    <span class="label label-success">
                                            Aprobado
                                    </span>
                                    <?php else: ?>
                                    <span class="label label-danger">
                                            Negado
                                    </span>
                                <?php endif; ?>
                            <?php break; ?>
                            <?php case 3: ?>
                                <span class="label label-danger">
                                    Negado
                                </span>
                            <?php break; ?>
                        <?php endswitch; ?>
                    </td>
                    <td>
                        <a href='<?php echo $this->url('account', array('controller' => 'OrderHistory', 'action' => 'detail', 'id' => $order->order_id)) ?>'>Detalles</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
        <?php else: ?>
            <h1>No existen ordenes realizadas</h1>
        <?php endif; ?>
        
        <div class="col-lg-12 clearfix">
          <ul class="pager">
            <li class="previous pull-right"><a href="<?php echo $this->url('catalog', array('controller' => 'franchise', 'action' => 'list')) ?>"><i class="fa fa-home"></i> ir a la tienda</a></li>
            <li class="next pull-left"><a href="<?php echo $this->url('account', array('controller' => 'index', 'action' => 'index')) ?>"> &larr; volver a mi cuenta</a></li>
          </ul>
        </div>
      </div>
      <!--/row end--> 
      
    </div>
  </div>
  <!--/row-->
  
  <div style="clear:both"></div>
</div>
<!-- /main-container -->

<div class="gap"> </div>

<!-- include footable plugin --> 
<?php $this->inlineScript()->appendFile($this->basePath('/assets/js/footable.js')); ?>

<?php $this->inlineScript()->captureStart();

 echo <<<JS
    $(function() {
      $('.footable').footable();
    });
JS;

$this->inlineScript()->captureEnd(); 
?>
